### ISSUE TITLE
Addressing reflections & deprecations for modern Java

### ISSUE THREAD

**Issue by Xemorr** [IntellectualSites/FastAsyncWorldEdit#396]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

Config.yml = https://hasteb.in/muqahavu.yaml
Latest log = 
```
[15:33:02] [Server thread/INFO]: Starting minecraft server version 1.15.2
[15:33:02] [Server thread/INFO]: Loading properties
[15:33:02] [Server thread/INFO]: This server is running Paper version git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[15:33:03] [Server thread/INFO]: Debug logging is disabled
[15:33:03] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:33:03] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:33:03] [Server thread/INFO]: Default game type: SURVIVAL
[15:33:03] [Server thread/INFO]: Generating keypair
[15:33:03] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:33:03] [Server thread/INFO]: Using default channel type
[15:33:11] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@364beb72]
[15:33:11] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[15:33:11] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_15_R2 as the Bukkit adapter
[15:33:12] [Server thread/INFO]: Ignoring invalid block minecraft:sign
[15:33:12] [Server thread/INFO]: Ignoring invalid block minecraft:wall_sign
[15:33:15] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v1.15-164;5cc7a09
[15:33:15] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.15.2
[15:33:15] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v3.0.0-SNAPSHOT
[15:33:15] [Server thread/INFO]: [ViaVersion] ViaVersion 3.0.0-SNAPSHOT is now loaded, injecting!
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 block mapping...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 item mapping...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading new 1.13 tags...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 enchantment mapping...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 sound mapping...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.12.2 -> 1.13 plugin channel mappings...
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading translation mappping
[15:33:16] [Server thread/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 blockstate mapping...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 block mapping...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 item mapping...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 sound mapping...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.14 blockstates...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.14 heightmap data...
[15:33:17] [Server thread/INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 blockstate mapping...
[15:33:18] [Server thread/INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 block mapping...
[15:33:18] [Server thread/INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 item mapping...
[15:33:18] [Server thread/INFO]: [ViaVersion] Loading 1.14.4 -> 1.15 sound mapping...
[15:33:18] [Server thread/INFO]: [ViaVersion] Loading 1.15 -> 1.16 blockstate mapping...
[15:33:25] [Server thread/INFO]: [ViaVersion] Loading 1.15 -> 1.16 block mapping...
[15:33:25] [Server thread/INFO]: [ViaVersion] Loading 1.15 -> 1.16 item mapping...
[15:33:25] [Server thread/INFO]: [ViaVersion] Loading 1.15 -> 1.16 sound mapping...
[15:33:25] [Server thread/INFO]: [Essentials] Loading Essentials v2.17.2.43
[15:33:25] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect v2.17.2.43
[15:33:25] [Server thread/INFO]: [ESCombat2] Loading ESCombat2 v1.0-SNAPSHOT
[15:33:25] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.17.2.43
[15:33:25] [Server thread/INFO]: [ViaBackwards] Loading ViaBackwards v3.0.0-SNAPSHOT
[15:33:25] [Server thread/INFO]: [EssentialsGeoIP] Loading EssentialsGeoIP v2.17.2.43
[15:33:25] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.2-SNAPSHOT;bf2593e
[15:33:25] [Server thread/INFO]: [ViaRewind] Loading ViaRewind v1.5.0-SNAPSHOT
[15:33:25] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:33:25] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v3.0.0-SNAPSHOT
[15:33:25] [Server thread/INFO]: [ViaBackwards] Loading translations...
[15:33:25] [Server thread/INFO]: [ViaBackwards] Registering protocols...
[15:33:26] [Server thread/INFO]: [ViaBackwards] Loading 1.13 -> 1.12.2 mappings...
[15:33:27] [Server thread/INFO]: [ViaBackwards] Loading 1.14 -> 1.13.2 mappings...
[15:33:31] [Server thread/INFO]: [ViaBackwards] Loading 1.15 -> 1.14.4 mappings...
[15:33:37] [Server thread/INFO]: [ViaBackwards] Loading 1.16 -> 1.15.2 mappings...
[15:33:50] [Server thread/INFO]: [ViaRewind] Enabling ViaRewind v1.5.0-SNAPSHOT
[15:33:51] [Server thread/INFO]: Preparing level "world"
[15:33:51] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[15:33:53] [Server thread/INFO]: Loaded 6 recipes
[15:33:54] [Server thread/INFO]: -------- World Settings For [world] --------
[15:33:54] [Server thread/INFO]: View Distance: 10
[15:33:54] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:33:54] [Server thread/INFO]: Item Merge Radius: 2.5
[15:33:54] [Server thread/INFO]: Item Despawn Rate: 6000
[15:33:54] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[15:33:54] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:33:54] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:33:54] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Carrot Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Potato Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Kelp Growth Modifier: 100%
[15:33:54] [Server thread/INFO]: Mob Spawn Range: 8
[15:33:54] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:33:54] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[15:33:54] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:33:54] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:33:54] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[15:33:54] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:33:54] [Server thread/INFO]: Max TNT Explosions: 100
[15:33:54] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[15:33:54] [Server thread/INFO]: Preparing start region for dimension 'world'/minecraft:overworld
[15:33:55] [Server thread/INFO]: Preparing spawn area: 0%
[15:33:55] [Server thread/INFO]: Preparing spawn area: 0%
[15:33:55] [Server thread/INFO]: Preparing spawn area: 0%
[15:33:56] [Server thread/INFO]: Preparing spawn area: 3%
[15:33:56] [Server thread/INFO]: Preparing spawn area: 4%
[15:33:56] [Server thread/INFO]: Preparing spawn area: 23%
[15:33:57] [Server thread/INFO]: Preparing spawn area: 59%
[15:33:58] [Server thread/INFO]: Preparing spawn area: 62%
[15:33:58] [Server thread/INFO]: Preparing spawn area: 97%
[15:33:58] [Server thread/INFO]: Preparing spawn area: 100%
[15:33:59] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:00] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:00] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:00] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:01] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:01] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:02] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server-Worker-1/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:06] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:07] [Server-Worker-1/INFO]: Preparing spawn area: 100%
[15:34:08] [Server-Worker-1/INFO]: Preparing spawn area: 100%
[15:34:08] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:08] [Server thread/INFO]: Preparing spawn area: 100%
[15:34:09] [Server thread/INFO]: Loaded 441 spawn chunks for world world
[15:34:09] [Server thread/INFO]: Time elapsed: 14569 ms
[15:34:09] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.15.2
[15:34:09] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v3.0.0-SNAPSHOT
[15:34:09] [Server thread/INFO]: [Essentials] Enabling Essentials v2.17.2.43
[15:34:09] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[15:34:09] [Server thread/INFO]: [Essentials] No kits found to migrate.
[15:34:09] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[15:34:09] [Server thread/INFO]: [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
[15:34:09] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[15:34:09] [Server thread/INFO]: [Essentials] Loaded 21019 items from items.json.
[15:34:09] [Server thread/INFO]: [Essentials] Using locale en_GB
[15:34:10] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[15:34:10] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[15:34:10] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[15:34:10] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.17.2.43
[15:34:10] [Server thread/INFO]: [EssentialsProtect] Continuing to enable Protect.
[15:34:10] [Server thread/INFO]: [ESCombat2] Enabling ESCombat2 v1.0-SNAPSHOT
[15:34:10] [Server thread/WARN]: [ESCombat2] "ESCombat2 v1.0-SNAPSHOT" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void me.xemor.escombat2.me.xemor.escombat2.random.EndPortalBlock.blockEndPortalCreation(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Xemor_].
[15:34:10] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.17.2.43
[15:34:10] [Server thread/INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP v2.17.2.43
[15:34:10] [Server thread/ERROR]: [EssentialsGeoIP] No license key found! Please visit https://essentialsx.cf/geoip for first time setup instructions.
[15:34:10] [Server thread/ERROR]: [EssentialsGeoIP] Failed to read GeoIP database!
java.io.FileNotFoundException: plugins\EssentialsGeoIP\GeoIP2-Country.mmdb (The system cannot find the file specified)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:345) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:214) ~[?:?]
	at com.maxmind.db.BufferHolder.<init>(BufferHolder.java:19) ~[?:?]
	at com.maxmind.db.Reader.<init>(Reader.java:116) ~[?:?]
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:66) ~[?:?]
	at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:54) ~[?:?]
	at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:160) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.reloadConfig(EssentialsGeoIPPlayerListener.java:162) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.<init>(EssentialsGeoIPPlayerListener.java:43) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIP.onEnable(EssentialsGeoIP.java:31) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-162]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:34:10] [Server thread/INFO]: [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
[15:34:10] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.2-SNAPSHOT;bf2593e
[15:34:11] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[15:34:11] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[15:34:11] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[15:34:11] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[15:34:11] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[15:34:11] [Server thread/INFO]: [WorldGuard] Loading region data...
[15:34:13] [Server thread/INFO]: Done (22.560s)! For help, type "help"
[15:34:13] [Server thread/INFO]: Timings Reset
[15:34:13] [Server thread/WARN]: [WorldEdit] Loaded class com.sk89q.worldguard.bukkit.WorldGuardPlugin from WorldGuard v7.0.2-SNAPSHOT;bf2593e which is not a depend, softdepend or loadbefore of this plugin.
[15:34:13] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.15.2(578)
[15:34:15] [Server thread/WARN]: [ViaVersion] You are running a development version, please report any bugs to GitHub.
[15:34:18] [User Authenticator #1/INFO]: UUID of player Xemor_ is bdea3203-c062-4616-93c0-e18028129ee9
[15:34:20] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ESCombat2 v1.0-SNAPSHOT
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setViewDistance(CraftPlayer.java:2005) ~[patched_1.15.2.jar:git-Paper-162]
	at me.xemor.escombat2.me.xemor.escombat2.commands.setRenderDistance.onPlayerJoin(setRenderDistance.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-162]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-162]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-162]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-162]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:34:20] [Server thread/INFO]: Xemor_[/127.0.0.1:52030] logged in with entity id 163 at ([world]-2296.2427332117563, 102.0515307100176, 2227.9129754806067)
[15:34:29] [Server thread/INFO]: Xemor_ issued server command: /fawe version
[15:34:35] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5266ms or 105 ticks behind
[15:35:02] [Server thread/INFO]: Xemor_ issued server command: /version
[15:36:22] [Server thread/INFO]: Xemor_ issued server command: /plugins
[15:36:32] [Server thread/INFO]: Plugins (11): ESCombat2, Essentials, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard
[15:37:59] [Server thread/INFO]: Xemor_ issued server command: /fawe debugpaste
```
Legacy YML = https://hasteb.in/onuturiy.yaml
**[REQUIRED] FastAsyncWorldEdit Version Number:** 

Bukkit-Official(1.15-164;5cc7a09)
**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.boydti.fawe.util.ReflectionUtils (file:/C:/Users/samue/Desktop/Minecraft%201.15/plugins/FastAsyncWorldEdit-1.15-164(2).jar) to field java.lang.Enum.ordinal
WARNING: Please consider reporting this to the maintainers of com.boydti.fawe.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This appears in console

**How to replicate**:

Use JRE 11

**Plugins being used on the server:**

[15:36:32 INFO]: Plugins (11): ESCombat2, Essentials, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard
**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by CCCoderDE** [comment]
I can confirm this occurs in Java Version 14 as well. (Version Bukkit-Official 1.16-306)

**Comment by aurorasmiles** [comment]
Can't replicate anymore, assuming it is fixed

**Comment by Eletroboss** [comment]
It still continues on PowerNukkit v1.3.2.0-PN-ALPHA.1 which I assume is the same as nukkit (I remember nukkit having the error too), with FastAsyncWorldEdit v19.11.13-5505943-1282-22.3.5 and DbLib v0.2.2

**Comment by Eletroboss** [comment]
It still continues on spigot (`This server is running CraftBukkit version git-Spigot-57bbdd8-dea4138 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`) with `FastAsyncWorldEdit v1.16-369;aed6807` and `VoxelSniper v1.0.3-backward`
with this error:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by protocolsupport.utils.ReflectionUtils (file:/home/pi/1.16.3%20new%20Creative/plugins/ProtocolSupport.jar) to field java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP
WARNING: Please consider reporting this to the maintainers of protocolsupport.utils.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
The plugins are:
BukkitOpFix
FastAsyncWorldEdit-1.16-369.jar
FastAsyncVoxelSniper-flattened-1.0.3-backward
ProtocolSupportLegacyChest-1.16.2.jar
ProtocolSupport

**Comment by dordsor21** [comment]
That's not FAWE?

**Comment by Xemorr** [comment]
Sorry, what?

**Comment by SirYwell** [comment]
@aurorasmiles marked this issue as can't replicate *almost 4 months ago*. If you still encounter that issue with the latest version, feel free to provide logs. THat's how it works.

**Comment by Xemorr** [comment]
I understand perfectly well how it works, and someone was able to replicate it.

**Comment by SirYwell** [comment]
This isn't ProtocolSupport, as already mentioned. If you can replicate with FAWE causing that message, we'll reopen this issue.

**Comment by Kruemmelspalter** [comment]
I also get this. Server: `Purpur version git-Purpur-965 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
Logs:
```
System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.10+8) Host: Linux 5.10.7-3-MANJARO (amd64)
Loading libraries, please wait...
[14:59:44 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:59:44 INFO]: Reloading ResourceManager: Default, bukkit
[14:59:45 INFO]: Loaded 7 recipes
[14:59:46 INFO]: Starting minecraft server version 1.16.5
[14:59:46 INFO]: Loading properties
[14:59:46 INFO]: This server is running Purpur version git-Purpur-965 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:59:46 INFO]: Debug logging is disabled
[14:59:46 INFO]: Server Ping Player Sample Count: 12
[14:59:46 INFO]: Using 4 threads for Netty based IO
[14:59:46 INFO]: Default game type: SURVIVAL
[14:59:46 INFO]: Generating keypair
[14:59:46 INFO]: Starting Minecraft server on *:25565
[14:59:46 INFO]: Using epoll channel type
[14:59:46 INFO]: Tuinity: Using libdeflate (Linux x86_64) compression from Velocity.
[14:59:46 INFO]: Tuinity: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[14:59:46 INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.16-581;dd65cff
[14:59:47 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@528db519]
[14:59:47 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:59:47 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.16-581;dd65cff
[14:59:47 INFO]: WEPIF: Using the Bukkit Permissions API.
[14:59:47 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R3 as the Bukkit adapter
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.boydti.fawe.util.ReflectionUtils (file:/projects/MC/Server/1.16.5/Purpur/plugins/FastAsyncWorldEdit-1.16-581.jar) to field java.lang.Enum.ordinal
WARNING: Please consider reporting this to the maintainers of com.boydti.fawe.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[14:59:47 INFO]: Ignoring invalid block minecraft:sign
[14:59:47 INFO]: Ignoring invalid block minecraft:wall_sign
[14:59:48 INFO]: Preparing level "world"
[14:59:48 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[14:59:48 INFO]: Preparing start region for dimension minecraft:overworld
[14:59:48 INFO]: Loaded 0 spawn chunks for world world
[14:59:48 INFO]: Preparing spawn area: 0%
[14:59:48 INFO]: Preparing spawn area: 3%
[14:59:49 INFO]: Time elapsed: 615 ms
[14:59:49 INFO]: Preparing start region for dimension minecraft:the_nether
[14:59:49 INFO]: Loaded 0 spawn chunks for world world_nether
[14:59:49 INFO]: Preparing spawn area: 0%
[14:59:49 INFO]: Time elapsed: 122 ms
[14:59:49 INFO]: Preparing start region for dimension minecraft:the_end
[14:59:49 INFO]: Loaded 0 spawn chunks for world world_the_end
[14:59:49 INFO]: Preparing spawn area: 0%
[14:59:49 INFO]: Time elapsed: 442 ms
[14:59:49 INFO]: Running delayed init tasks
[14:59:49 INFO]: Done (3.584s)! For help, type "help"
[14:59:49 INFO]: Timings Reset
```

**Comment by SirYwell** [comment]
As a note: To resolve this, we need to rework the PropertyKey enum.

**Comment by NotMyFault** [comment]
More reflections we'll need to take care of in the future: https://paste.gg/p/anonymous/5bb6c3817b26495aa16ededa0f9435b3
Currently tested on Java 17.

**Comment by MattBDev** [comment]
@NotMyFault Yay. More reflections that broke in Java 17 😒

**Comment by almandoro** [comment]
Hello,

After server loads ( PaperMC 1.16.5 ) I see this error in console from FAWE:

....WARNING: An illegal reflective access operation has occurred
--
  | WARNING: Illegal reflective access by com.boydti.fawe.object.collection.CleanableThreadLocal (file:/data/plugins/FastAsyncWorldEdit-Bukkit-1.16-666.jar) to field java.lang.Thread.threadLocals
  | WARNING: Please consider reporting this to the maintainers of com.boydti.fawe.object.collection.CleanableThreadLocal
  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  | WARNING: All illegal access operations will be denied in a future release
  | [15:15:44 INFO]: Higher left the game


Error log (if applicable)
https://paste.gg/p/anonymous/db18763b53c842b6865a605d24fa3188

Fawe Debugpaste
https://athion.net/ISPaster/paste/view/df5930d6f14d40c2968d431890fbbbf3

**Comment by LaurenceBarnes** [comment]
Given that this is a Java 16 issue afaik, this

https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

probably adds some relevance, as it looks like 1.17 is going to be on the most recent Java version.

**Comment by NotMyFault** [comment]
> Given that this is a Java 16 issue afaik, this
> 
> https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a
> 
> probably adds some relevance, as it looks like 1.17 is going to be on the most recent Java version.

I don't bother too much with 16 in particular when looking on 1.17 and future updates, as 16 will be EOL in September 2021.
Speaking of 1.17, announced as "summer update", that version may not used more than 2 months from the actual release date before reaching it's EOL and people (hopefully/sanely) use the next major LTS, 17, which we are targeting on.

**Comment by LaurenceBarnes** [comment]
Well of course, the thing is, that it looks like Java 16 will be required in 1.17, and people assume that 1.18 in winter will then ship with Java 17 LTS. Probably the differences between Java 16 and 17 won't be as huge as the ones between Java 16 and 8/11 ^-^
It would just be awesome if FAWE would still work on MC 1.17

**Comment by SirYwell** [comment]
LTS or not doesn't really matter for almost all users, and for now, Java 17 doesn't add more changes that are relevant for us. But we really need to figure out solutions for the remaining issues with strongly encapsulated jdk internals. Maybe we should start working on Java 16+ only builds, as that would help using newer, recommended methods for the stuff we're doing.

**Comment by LaurenceBarnes** [comment]
yeah, that sounds promising.
